// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBto0muHwlzF3toFenlWizT2j0sFfxu_M',
    appId: '1:526316328180:web:6256c93fec47646afbfaa1',
    messagingSenderId: '526316328180',
    projectId: 'moh-flower-shop',
    authDomain: 'moh-flower-shop.firebaseapp.com',
    storageBucket: 'moh-flower-shop.firebasestorage.app',
    measurementId: 'G-YW00RYM6W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEzWjI_NE0VwCco2-SjB8dvsTJ6BfVMd4',
    appId: '1:526316328180:android:49b9db2d563f7666fbfaa1',
    messagingSenderId: '526316328180',
    projectId: 'moh-flower-shop',
    storageBucket: 'moh-flower-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOAguX8HAUHfiVdrpY-tPUBxFQd6thkG8',
    appId: '1:526316328180:ios:d5f430b5059f7441fbfaa1',
    messagingSenderId: '526316328180',
    projectId: 'moh-flower-shop',
    storageBucket: 'moh-flower-shop.firebasestorage.app',
    iosBundleId: 'com.example.flowerShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOAguX8HAUHfiVdrpY-tPUBxFQd6thkG8',
    appId: '1:526316328180:ios:d5f430b5059f7441fbfaa1',
    messagingSenderId: '526316328180',
    projectId: 'moh-flower-shop',
    storageBucket: 'moh-flower-shop.firebasestorage.app',
    iosBundleId: 'com.example.flowerShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBto0muHwlzF3toFenlWizT2j0sFfxu_M',
    appId: '1:526316328180:web:6ea713235ee6dca2fbfaa1',
    messagingSenderId: '526316328180',
    projectId: 'moh-flower-shop',
    authDomain: 'moh-flower-shop.firebaseapp.com',
    storageBucket: 'moh-flower-shop.firebasestorage.app',
    measurementId: 'G-1DC3J31FGH',
  );
}
